# Generated by Django 4.2.7 on 2023-11-08 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_wishlist', '0002_place_date_vistied_place_notes_place_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='date_vistied',
            new_name='date_visited',
        ),
    ]
